### ISSUE TITLE
Cannot install pyequion2 with python 3.9

### ISSUE THREAD

**Issue by yuegengma** [pyequion/pyequion#1]
Trying to install this package on my PC (Windows 10 conda environment), but failed with the following issue

(base) C:\Users\myg\Desktop>pip3 install pyequion2-0.0.6.3.tar.gz
Processing c:\users\myg\desktop\pyequion2-0.0.6.3.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\Anaconda\python.exe' 'D:\Anaconda\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\myg\AppData\Local\Temp\tmpimzz5uo_'
       cwd: C:\Users\myg\AppData\Local\Temp\pip-req-build-yw7f2h7t
  Complete output (63 lines):
  running egg_info
  writing pyequion2.egg-info\PKG-INFO
  writing dependency_links to pyequion2.egg-info\dependency_links.txt
  writing requirements to pyequion2.egg-info\requires.txt
  writing top-level names to pyequion2.egg-info\top_level.txt
  reading manifest file 'pyequion2.egg-info\SOURCES.txt'
  setup.py:45: UserWarning: Could not install with cython module. Installing pure python
    warnings.warn("Could not install with cython module. Installing pure python")
  Traceback (most recent call last):
    File "setup.py", line 26, in <module>
      setup(
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\__init__.py", line 86, in setup
      _install_setup_requires(attrs)
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\__init__.py", line 80, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\build_meta.py", line 62, in fetch_build_eggs
      raise SetupRequirementsError(specifier_list)
  setuptools.build_meta.SetupRequirementsError: ['setuptools>=18.0', 'cython']

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "D:\Anaconda\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "D:\Anaconda\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "D:\Anaconda\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\build_meta.py", line 177, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires
      self.run_setup()
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 46, in <module>
      setup(
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 177, in setup
      return run_commands(dist)
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 193, in run_commands
      dist.run_commands()
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
      self.run_command(cmd)
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\dist.py", line 1229, in run_command
      super().run_command(command)
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
      cmd_obj.run()
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 308, in run
      self.find_sources()
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 315, in find_sources
      mm.run()
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 550, in run
      self.add_defaults()
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 594, in add_defaults
      self.read_manifest()
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\command\sdist.py", line 195, in read_manifest
      self.filelist.append(line)
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 492, in append
      path = convert_path(item)
    File "C:\Users\myg\AppData\Local\Temp\pip-build-env-y79raq4k\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 138, in convert_path
      raise ValueError("path '%s' cannot be absolute" % pathname)
  ValueError: path '/home/dfnaiff/Danilo/NIDF/Projects/PyEquion2/pyequion/pyequion2/activity/coo_tensor_ops/coo_tensor_ops.c' cannot be absolute
  ----------------------------------------
WARNING: Discarding file:///C:/Users/myg/Desktop/pyequion2-0.0.6.3.tar.gz. Command errored out with exit status 1: 'D:\Anaconda\python.exe' 'D:\Anaconda\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\myg\AppData\Local\Temp\tmpimzz5uo_' Check the logs for full command output.
ERROR: Command errored out with exit status 1: 'D:\Anaconda\python.exe' 'D:\Anaconda\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\myg\AppData\Local\Temp\tmpimzz5uo_' Check the logs for full command output.

**Comment by Pandadude3000** [comment]
Still getting this error with win10 conda python 3.9, despite updating pip and cython, and importing cython manually:

pip install pyequion2

Collecting pyequion2
  Using cached pyequion2-0.0.6.3.tar.gz (205 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?2164c9a7-988a-4501-8bde-95375cbaa45c)
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      <string>:45: **UserWarning: Could not install with cython module.** Installing pure python
      running egg_info
      writing pyequion2.egg-info\PKG-INFO
      writing dependency_links to pyequion2.egg-info\dependency_links.txt
      writing requirements to pyequion2.egg-info\requires.txt
      writing top-level names to pyequion2.egg-info\top_level.txt
      reading manifest file 'pyequion2.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 26, in <module>
        File "C:\Users\alvir\AppData\Local\Temp\pip-build-env-uiyhyz01\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "C:\Users\alvir\AppData\Local\Temp\pip-build-env-uiyhyz01\overlay\Lib\site-packages\setuptools\__init__.py", line 80, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "C:\Users\alvir\AppData\Local\Temp\pip-build-env-uiyhyz01\overlay\Lib\site-packages\setuptools\__init__.py", line 85, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\Users\alvir\AppData\Local\Temp\pip-build-env-uiyhyz01\overlay\Lib\site-packages\setuptools\build_meta.py", line 74, in fetch_build_eggs
          raise SetupRequirementsError(specifier_list)
      setuptools.build_meta.**SetupRequirementsError: ['setuptools>=18.0', 'cython']**
      
      During handling of the above exception, another exception occurred:
...
│ exit code: 1
╰─> See above for output.
